"""add creator_id to ticket

Revision ID: e3d45b767ea4
Revises: c5227e81e573
Create Date: 2025-10-11 16:15:14.847675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3d45b767ea4'
down_revision: Union[str, Sequence[str], None] = 'c5227e81e573'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tickets', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'creator_id')
    # ### end Alembic commands ###
